export enum TaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum UnitClass {
  INFANTRY = 'INFANTRY', // Standard tasks
  HEAVY = 'HEAVY',       // Long duration tasks
  SCOUT = 'SCOUT',       // Quick tasks / emails
  HAZARD = 'HAZARD',     // Meetings (Unmoveable)
  PATROL = 'PATROL'      // Recurring events (Class schedules, routines)
}

export interface UnitStats {
  hp: number;
  attack: number;
  defense: number;
  apCost: number; // Action Points required to engage/complete
}

export interface TacticalUnit {
  id: string;
  title: string;
  description?: string;
  
  // Calendar Data
  startTime: Date; // For grid placement
  durationHours: number; // How many vertical grid cells
  
  // Game Data
  priority: TaskPriority;
  unitClass: UnitClass;
  stats: UnitStats;
  isComplete: boolean;
  
  // Sync Data
  syncStatus?: 'synced' | 'pending' | 'error';
  icalUid?: string; // Link to iCloud event
  
  // Flavor
  codename?: string; // Generated by AI
  flavorText?: string; // Generated by AI
}

export interface GridCoordinates {
  dayIndex: number; // 0-6 (Sun-Sat)
  hourIndex: number; // 0-23
}

export interface GameState {
  units: TacticalUnit[];
  actionPoints: {
    current: number;
    max: number;
  };
  selectedUnitId: string | null;
  fogOfWar: boolean; // Global toggle
  scoutedSectors: string[]; // "day-hour" strings
  lastSynced?: Date;
}

// Boss / Project Interfaces
export interface BossPhase {
  id: string;
  title: string;
  hp: number;
  isDefeated: boolean;
}

export interface ProjectBoss {
  id: string;
  name: string;
  totalHp: number;
  currentHp: number;
  phases: BossPhase[]; // Representing milestones or sub-epics
  deadline: Date;
  lore: string;
}

// Internal Calendar Types
export interface CalendarEvent {
  uid: string;
  summary: string;
  description?: string;
  start: Date;
  end: Date;
  isRecurring: boolean;
  location?: string;
}
